version: '3.8'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: "./services/client"
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./services/client:/app
  server:
    build: services/server
    ports:
      - "8080:8080"
