version: '3.8'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: "./services/client"
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./services/client:/app
  server:
    # Hot-reaload for GO thanks to https://github.com/cosmtrek/air
    image: cosmtrek/air
    working_dir: /services/server
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./services/server/:/services/server
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
