version: '3.8'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: "./services/client"
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./services/client:/app
  server:
    # Hot-reaload for GO thanks to https://github.com/cosmtrek/air
    image: cosmtrek/air
    working_dir: /services/server
    ports:
      - "8080:8080"
    volumes:
      - ./services/server/:/services/server
